### ISSUE TITLE
Fix preference screen issues

### ISSUE THREAD

**Issue by sabiou** [sabiou/depensy-wip#12]
![bug-prefs-screen](https://user-images.githubusercontent.com/25927652/55302133-a504cb00-5437-11e9-9d43-9a0e2e5bbd26.png)

**Comment by adityasonel** [comment]
Hi @sabiou, you are doing a great job man. I can contribute to your project. I'm interested in your project. What do you think?

**Comment by sabiou** [comment]
Hi @adityasonel glad you're interested.  :smile: feel free to contribute, you are welcome.

**Comment by adityasonel** [comment]
Hi @sabiou, everything fines while building the project. But there are some resources missing in current commit 3664e4d0bb898a6c95dcbea956029bfa0305ded1. For example @drawable/background_gradient, color resource file, dimens resource file, fonts, and some styles.

**Comment by sabiou** [comment]
Hi @adityasonel  it's because I have pushed some changes to the master branch since your fork. Now you have to sync your fork in order to keep it up to date.

**Comment by sabiou** [comment]
Check this if u need any it can help on how to do this https://help.github.com/en/articles/syncing-a-fork

**Comment by sabiou** [comment]
I'm doing some changes to the master branch before keeping it appart.. from other features branches.

**Comment by adityasonel** [comment]
Yup mate, I didn't check that you have made some changes after I forked. Let me sync first. 😄

**Comment by sabiou** [comment]
Hi @adityasonel did you get it working?

**Comment by sabiou** [comment]
@adityasonel reach me out on Telegram https://t.me/godidev

**Comment by adityasonel** [comment]
@sabiou link is not working mate!

**Comment by sabiou** [comment]
@adityasonel click on open in web
